export const UNIT_OF_MEASURE_OPTIONS = [
  { value: 'unit', label: 'Unit' },
  { value: 'piece', label: 'Pieces' },
  { value: 'set', label: 'Set' },
  { value: 'pair', label: 'Pair' },
  { value: 'dozen', label: 'Dozen' },
  { value: 'pack', label: 'Pack' },
  { value: 'box', label: 'Box' },
  { value: 'bundle', label: 'Bundle' },
  { value: 'roll', label: 'Roll' },
  { value: 'sheet', label: 'Sheet' },
  { value: 'meter', label: 'Meter' },
  { value: 'centimeter', label: 'Centimeter' },
  { value: 'millimeter', label: 'Millimeter' },
  { value: 'foot', label: 'Foot' },
  { value: 'inch', label: 'Inch' },
  { value: 'square_foot', label: 'Square foot' },
  { value: 'square_meter', label: 'Square meter' },
  { value: 'kilogram', label: 'Kilogram' },
  { value: 'gram', label: 'Gram' },
  { value: 'liter', label: 'Liter' },
  { value: 'milliliter', label: 'Milliliter' },
  { value: 'thickness', label: 'Thickness' },
] as const;
